### ISSUE TITLE
cellNexus does not work with user made cache

### ISSUE THREAD

**Issue by stemangiola** [MangiolaLaboratory/cellNexus#17]
(@multimeric maybe you have a clue why)

If I create a cache manually cellNexus refuses to read it
 
get_single_cell_experiment(assay = "counts", atlas_name="cellxgene", cache_directory ="/vast/scratch/users/mangiola.s/cellNexus", repository = NULL)
 
and creates another identical directory
 
 
![image](https://github.com/user-attachments/assets/9bbb6fac-3a63-4a1b-8c79-802069478efd)

the user should be able to use cellNexus on their own directories, with their metadata. Now if cellNexus does not create the cache, it does not accept anything else
 
you can try yourself putting a h5ad in a random directory and try to call get_SCE
 
Michael might have suggestion on the code
 
(counts assay is not a problem because I changed X to counts in the code)

**Comment by multimeric** [comment]
The two directories can't have the same name. There must be something different about them. Please attach the output of `ls -l /vast/scratch/users/mangiola.s/cellNexus/cellxgene`.

**Comment by stemangiola** [comment]
My bad

```
drwxr-x---+ 2 mangiola.s allstaff 4096 Dec 18 16:19 ' 26-11-2024'
drwxr-x---+ 2 mangiola.s allstaff 4096 Dec 18 17:38  26-11-2024
```
